# Code

## Data Sourcing
```{r}
#| label: Load Packages and API Keys
#| include: false

source(paste(getwd(), "scripts/systemConfig.R", sep = "/"))


```


```{r}
#| label: Import BEA NIPA Data
#| warning: false
#| include: false

# Data includes Annual and Quartely
# - GDP
# - Personal Income and Its Disposition
source(paste(getwd(), "scripts/importBEA_NIPA.R", sep = "/"))

# Clean up
rm(nipaConfig,
   gdpA_list, gdpQ_list,
   pidA_list, pidQ_list)

```


```{r}
#| label: Import BEA: Foreign Direct Investment 
#| warning: false
#| include: false

source(paste(getwd(), "scripts/importBEA_FDI.R", sep = "/"))

```

```{r}
#| label: Import FRED Data 
#| warning: false

# Data Sources: 
# - CPI
# - Housing Starts
# - PPI: All Commodities
# - PPI: Final Demand
# - Unemployment

source(paste(getwd(), "scripts/importFRED.R", sep = "/"))

# clean up
rm(FFR_M, seriesTable)
```


```{r}
#| output: true
#| output-line-numbers: "here"

dataList <- c("FDI", "GDPA", "GDPQ", "PIDA", "PIDQ", "FFRM", "FFRA", "FFRQ",
               "coreInflation", "employment_cost_index", "housingStarts",
               "PPI", "unemploymentRate")

dataSummary <- tibble(source = as.character(),
                     yearSpan = as.numeric(),
                     obs = as.numeric(),
                     nCols = as.numeric(),
                     yearStart = as.numeric(),
                     yearEnd = as.numeric())

for (i in 1:length(dataList)) {
  
  tmpDf <- get(dataList[i])
  yearRange <- range(tmpDf[, 1])
  yearDiff <- yearRange[2] - yearRange[1]
  rObs <- nrow(tmpDf)
  cObs <- ncol(tmpDf)
  dataSummary <- dataSummary |>
    add_row(source = dataList[i],
            yearSpan = yearDiff,
            obs = rObs,
            nCols = cObs,
            yearStart = yearRange[1],
            yearEnd = yearRange[2])
  }
```

```{r}

recessionDates <- tibble(year = c(1958, 1958, 1960, 1960, 1960, 1961, 1970, 
                                  1970, 1970, 1970, 1974, 1974, 1974, 1974, 
                                  1975, 1980, 1980, 1980, 1981, 1981, 1982, 
                                  1982, 1982, 1982, 1990, 1990, 1991, 2001,
                                  2001, 2001, 2008, 2008, 2008, 2008, 2009,
                                  2009, 2020),
                         quarter = c("Q1", "Q2", "Q2", "Q3", "Q4", "Q1", "Q1", 
                                     "Q2", "Q3", "Q4", "Q1", "Q2", "Q3", "Q4", 
                                     "Q1", "Q1", "Q2", "Q3", "Q3", "Q4", "Q1",
                                     "Q2", "Q3", "Q4", "Q3", "Q4", "Q1", "Q2",
                                     "Q3", "Q4", "Q1", "Q2", "Q3", "Q4", "Q1",
                                     "Q2", "Q2"))
```

## Methodology
```{r}
annualYears <- 1958:2023

annualTbl <- merge(
  GDPA |> filter(year %in% annualYears) |> select(!source),
  FFRA |> filter(year %in% annualYears) |> select(!source),
  by = "year") |>
  merge(coreInflation |> 
          filter(year %in% annualYears & month == 12) |>
          select(!c(source, month, cpi, cpiDelta))) |>
  merge(unemploymentRate |> 
          filter(year %in% annualYears & month == 12) |>
          select(!c(source, month, unrateDelta)))

rownames(annualTbl) <- annualTbl[, 1]
```


```{r}
#| label: Global BallMapper Conditions

pcAnnual <- annualTbl[ ,c(2, 3, 8, 21, 15, 18, 26, 27, 29)]

pcAnnualClean <- annualTbl |>
  anti_join(recessionDates, by = "year") |>
  select(c(2, 3, 8, 21, 15, 18, 26, 27, 29))

  
annualCorr <- correlate(pcAnnual, quiet = TRUE) |>
  rename("GDP" = 2, "PCE" = 3, "Ig" = 4, "Gov" = 5, "Exports" = 6, 
         "Imports" = 7, "InterestRateA" = 8, "CPIA" = 9, "AvgUnrateA" = 10)
```


## Results

```{r}
#| label: Annual BM-single
#| include: false

pcAclean <- pcAnnualClean |> normalize_to_min_0_max_1()

pcA <- pcAnnual |> normalize_to_min_0_max_1()
coloring <- annualTbl$year |> as.data.frame()
e = 0.45

svglite("annualBM.svg", height = 6, width = 8)
annualBm <- BallMapper(points = pcA, values = coloring, epsilon = e)
ColorIgraphPlot(annualBm, seed_for_plotting = 29)
title(main = "BallMapper output Colored by Year",
      sub = paste("Epsilon", e, sep = ": "))
dev.off()
```


```{r}
#| label: Hide n Seek
#| eval: false

pcAnnual |>
  slice(points_covered_by_landmarks(annualBm, c(12:20))) |>
  rename("GDP" = 1, "PCE" = 2, "Ig" = 3, "Gov" = 4, "Exports" = 5, 
         "Imports" = 6, "FFR" = 7, "CPI" = 8, "UnRate" = 9)
```

## Appendix
```{r}
#| label: tbl-summarystats
#| tbl-cap: Summary Statistics (%)

summaryStatsA <- pcAnnual |>
  rename("GDP" = 1, "PCE" = 2, "Ig" = 3, "Exports" = 4, "Imports" = 5,
         "Gov" = 6, "InterestRateA" = 7, "CPIA" = 8, "AvgUnrateA" = 9) |>
  summarise(across(everything(), list(Minimum = min,
                                      Q25 = ~quantile(., 0.25),
                                      Median = median,
                                      Q75 = ~quantile(., 0.75),
                                      Maximum = max,
                                      Mean = mean,
                                      SD = sd,
                                      VAR = var))) |>
  pivot_longer(everything(), names_to = "var", values_to = "val") |>
  separate_wider_delim(var, delim = "_", 
                       names = c("measure", "statistic")) |>
  pivot_wider(names_from = statistic, values_from = val)

summaryStatsA |>
  kable(digits = 2)
```


```{r}
#| label: tbl-covidplus
#| tbl-cap: COVID-19+ (% change)

pcAnnual |>
  slice(points_covered_by_landmarks(annualBm, c(1, 16, 25, 27))) |>
  rename("GDP" = 1, "PCE" = 2, "Ig" = 3, "Gov" = 4, "Exports" = 5, 
         "Imports" = 6, "FFR" = 7, "CPI" = 8, "UnRate" = 9) |>
  kable()
```


```{r}
#| label: tbl-greatinflation
#| tbl-cap: The Great Inflation (% change)

pcAnnual |>
  slice(points_covered_by_landmarks(annualBm, c(12:20))) |>
  rename("GDP" = 1, "PCE" = 2, "Ig" = 3, "Gov" = 4, "Exports" = 5, 
         "Imports" = 6, "FFR" = 7, "CPI" = 8, "UnRate" = 9) |>
  kable()
```


```{r}
#| label: fig-yearspan
#| fig-cap: Year Coverage by Data Source

dataSummary |>
  filter(source %in% c("GDPA", "FFRA", "coreInflation", "unemploymentRate")) |>
  mutate(source =  c("BEA GDP", "FRB FFR", "BLS CPI", "BLS UnRate")) |>
  ggplot(aes(x = yearSpan,
             y = fct_reorder(source, yearSpan))) +
  geom_col(fill = "orchid4") +
  geom_text(aes(x = 0, label = yearSpan), hjust = -0.2) +
  labs(x = "Year Span", y = "Source") +
  xlim(0, 100) +
  theme(plot.title.position = 'plot')
```


```{r}
#| label: fig-corr
#| warning: false

annualCorr |>
  mutate(term = names(.)[-1]) |>
  shave() |>
  stretch() |>
  mutate(x = factor(x, levels = c("GDP", "PCE", "Ig", "Gov", "Exports", 
                                  "Imports", "InterestRateA", "CPIA", 
                                  "AvgUnrateA")),
         y = factor(y, levels = c("GDP", "PCE", "Ig", "Gov", "Exports", 
                                  "Imports", "InterestRateA", "CPIA", 
                                  "AvgUnrateA") |> rev())) |>
  ggplot(aes(x = x, y = y)) + 
  geom_tile(aes(fill = r)) +
  geom_text(aes(label = round(r, 2)), size = 3) +
  scale_fill_viridis(na.value = "white", limits = c(-1, 1)) +
  theme_minimal() +
  theme(axis.title = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 0.95, vjust = 1)) +
  labs(title = "TDA Point Cloud: Annual",
       subtitle = "Pearson Correlation Values",
       fill = "Correlation") +
  coord_cartesian(expand = FALSE)
```